### ISSUE TITLE
Allow downloading of the individual output files of the AWS Batch job

### ISSUE THREAD

**Issue by ivan-aksamentov** [nextstrain/cli#104]
**Context**  
During SARS-CoV-2 build maintenance, after a batch job is done, among numerous outputs often only one or two files need to be retrieved (to check a  successful build or to diagnose a build failure). However, currently, all files are compressed into a zip archive. Downloading and extracting the entire output zip, which nowadays can be a few gigabytes in size compressed and plus several gigabytes extracted, is wasteful and somewhat annoying for build maintainers.

**Description**   
It is proposed to allow downloading the individual output files of the AWS Batch job, without downloading the whole archive.

**Examples**

**Possible solution**   
(Optional)
Compress files separately, instead of making one large zip.

**Comment by tsibley** [comment]
:+1: for some way of addressing this need. A couple thoughts.

There is some overhead in transferring potentially thousands of small, individual files from/to S3. It'd be nice to avoid this overhead, or show that it's not actually significant to care about.

Some important metadata about each file is stored along with its contents in the ZIP. This metadata would for files stored directly in S3, unless we explicitly do more work to preserve it in and restore it from the object metadata.

ZIP archives support random access to files since they contain a listing with byte offsets. Similarly, S3 supports random access to objects via the HTTP Range header. This means we could keep the single big ZIP archive while still downloading only specific files. This would be my preferred solution. Filesystem-abstractions provided by [fsspec](https://filesystem-spec.readthedocs.io/en/latest/) (via [s3fs](https://s3fs.readthedocs.io/en/latest/)) support S3's random access transparently, and even provide some nice APIs over ZIP archives. Consider the following example:

```python
>>> import fsspec

>>> fs = fsspec.filesystem("zip", fo="s3://nextstrain-jobs/04cf5d35-fef9-4218-b63e-4f529fe00d8c.zip")

>>> fs.ls("")
['./', '.gitignore', 'README.md', 'Snakefile', 'config/', 'data/']

>>> fs.zip.extract("data/metadata.tsv", "/tmp")
'/tmp/data/metadata.tsv'
```

Behind the scenes, all the requests to S3 are made with Range headers to avoiding transferring the whole archive.

**Comment by tsibley** [comment]
Other things we'll need to consider is what the interface is for downloading just _some_ files from the build. Right now the only way to fetch files from a build (through the CLI) is attaching to an existing build and downloading everything.

**Comment by tsibley** [comment]
> Is a new option for `nextstrain build` a suitable design, or bolting on more cruft?

Suitable enough for now.

> Should this be a separate command?

Nah. (At least not without a larger redesign, which doesn't seem warranted.)
