### ISSUE TITLE
Cyrptic error message when downloading from AWS

### ISSUE THREAD

**Issue by rneher** [nextstrain/cli#109]
when downloading specific files from AWS, one gets a cryptic error message with the destination directory isn't empty:
```
(nextstrain) [neher@login20 ncov]$  nextstrain build --aws-batch --attach 7f01ca55-990c-4fe9-a2a2-c4b2b17c93b7 --download benchmarks/* .
Error: Build path "benchmarks/proximity_score_africa_region_late.txt" does not exist or is not a directory.

Perhaps your current working directory is different than you expect?
```
after `rm benchmarks/*` this works as expected. 

This is on `3.0.1`

**Comment by tsibley** [comment]
What happened here is that your shell expanded the wildcard before running `nextstrain build`, e.g.:

    nextstrain build --aws-batch --attach 7f01ca55-990c-4fe9-a2a2-c4b2b17c93b7 --download benchmarks/foo.txt benchmarks/bar.txt benchmarks/baz.txt .

Since `--download` only takes one argument, the next argument (`benchmarks/proximity_score_africa_region_late.txt` in your case) was taken as the build dir (instead of `.`).

The solution is to quote the pattern passed to `--download`, as in:

    nextstrain build --aws-batch --attach 7f01ca55-990c-4fe9-a2a2-c4b2b17c93b7 --download "benchmarks/*" .

I wouldn't consider this a bug, but perhaps there's an opportunity to improve documentation here. Is there a place in the doc or `--help` output where you would have seen a suggestion to quote the argument to `--download`?

**Comment by rneher** [comment]
thanks! Maybe add something like the italic bit to cli help?

Only download modified files matching <pattern> from the remote build. Basic shell-style globbing is supported, *but make sure to escape or quote the pattern*. May be passed more than once. Currently only supported when also using --aws-batch. (default: True)

**Comment by tsibley** [comment]
Done! Thanks.
