### ISSUE TITLE
Warning in nextalign and treetime

### ISSUE THREAD

**Issue by EricFournier3** [nextstrain/cli#127]
**Current Behavior**  
A clear and concise description of what is happening / what the bug is.  

I ran a build named testbuildQuatre and I see some unexpected WARNING in logs/aamuts_testbuildQuatre.txt and align_testbuildQuatre-Data.txt;
 - WARNING: Number of tips in tree differs from number of sequences in alignment!
 - WARNING: TreeAnc._attach_sequences_to_nodes: NO SEQUENCE FOR LEAF: Canada/Qc-L00355579/2020 (**but I clearly see Canada/Qc-L00355579/2020 in testbuildQuatre_subsampled_sequences.fasta.xz**)
 - WARNING: TreeAnc: 2 nodes don't have a matching sequence in the
        alignment. POSSIBLE ERROR

I also see many Warning in align_testbuildQuatre-Data.txt (see attached file)

**Expected behavior**  
A clear and concise description of what you expected to happen instead.  

I didn't expect such WARNING. Is it possible to have explanation regarding them? Does it have an  impact on the final phylogeny ?

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Open / run ...  
2.   
3.  

**Possible solution**  
(optional)  

**Your environment: if browsing Nextstrain online**  
 - Operating system:  
 - Browser:  

**Your environment: if running Nextstrain locally**  
 - Operating system:   CentOS 7
 - Browser:  
 - Version (e.g. `auspice 2.7.0`):  nextstrain.cli 3.0.3, treetime 0.8.1, augur 12.0.0

**Additional context**  

Thank you
Eric

[aamuts_testbuildQuatre.txt](https://github.com/nextstrain/cli/files/7032607/aamuts_testbuildQuatre.txt)
[align_testbuildQuatre-Data.txt](https://github.com/nextstrain/cli/files/7032608/align_testbuildQuatre-Data.txt)
![nextstrain_version](https://user-images.githubusercontent.com/15850682/130462656-37c2091e-f545-4199-9c69-802284f5b015.PNG)

**Comment by rneher** [comment]
hi Eric,

thanks for raising this. This likely has to do with a sequence that nextalign didn't translate because of frameshift of because the corresponding gene wasn't covered. In this case, the aminoacid sequence of the respective gene is missing for that strain and amino acid mutations can't be reconstructed. This shouldn't affect the phylogeny. 

we will improve the way translations are handled in nextalign and the workflow soon. 
best,
richard

**Comment by EricFournier3** [comment]
Ok thank you Richard,

and can you please explain me why I got the following Warning in aamuts_testbuildQuatre.txt

WARNING: Number of tips in tree differs from number of sequences in alignment!
WARNING: TreeAnc._attach_sequences_to_nodes: NO SEQUENCE FOR LEAF: Canada/Qc-L00355579/2020 (**but I clearly see Canada/Qc-L00355579/2020 in testbuildQuatre_subsampled_sequences.fasta.xz**)
WARNING: TreeAnc: 2 nodes don't have a matching sequence in the
alignment. POSSIBLE ERROR

Best,

**Comment by tsibley** [comment]
@EricFournier3 

I believe Richard's explanation:

> This likely has to do with a sequence that nextalign didn't translate because of frameshift of because the corresponding gene wasn't covered.

addresses that warning too. The sequence `Canada/Qc-L00355579/2020` is in the input data but wasn't translated by Nextalign for the reasons Richard gave. The tip for the sequence still exists in the tree, so during AA mutation calculation, TreeTime warns that it found a tip which wasn't in the amino acid alignment.

I'm closing this issue because it's not about a bug in the Nextstrain CLI itself. If you'd like more help running Nextstrain workflows, the team also fields questions on our https://discussion.nextstrain.org site, which is a better venue for this sort of thing.

**Comment by EricFournier3** [comment]
Great @tsibley , thank you again
