### ISSUE TITLE
BUG: Bioconda installed cli asks for upgrade via pip, it shouldn't

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/cli#204]
### Current Behavior
I've got nextstrain-cli installed through bioconda.

When a new cli version is available via pip, it prompts me to upgrade via pip, this is not good - it would potentially screw up the conda environment

### Expected behavior
Tell the user that bioconda does not have the latest version (yet) -> this would be productive thing to do: why isn't bioconda up to date, users could approve the PR, rather than ask them to install via pip, screwing up the environment

### How to reproduce
1. Install outdated version of nextstrain cli from bioconda into conda environment
2. run `nextstrain update`
3. Observe results

### Possible solution
1. Identify if one runs pip or conda installed nextstrain cli (inspect path?)
2. Adapt message to way this was installed. Either not say anything for conda, or say you may want to comment on the PR

To speed up approval of autobumps on bioconda, we should make more nextstrain core people part of bioconda, e.g. @victorlin, but generally anyone on @nextstrain/core really

I added myself as maintainer, but we should probably add more people here in general: https://github.com/bioconda/bioconda-recipes/pull/35899/files#diff-3a2dea95db8f09a16f883aa85ba5cfbad25cf3a0eea2febc3ef40e9b99ce3920L64

Maybe bioconda approval can be added to nextstrain-cli release checklist, too

@tsibley

**Comment by corneliusroemer** [comment]
Maybe fixed in [#194](https://github.com/nextstrain/cli/pull/194)

**Comment by tsibley** [comment]
Not fixed by #194. This is a known issue, tracked by https://github.com/nextstrain/cli/issues/114. Closing as duplicate.

**Comment by tsibley** [comment]
Agreed we should add more folks from the team as maintainers of the Bioconda recipes. I think it'd be reasonable to only include the folks actually likely to do the work, i.e. not the whole @nextstrain/core. But I wonder if we could list the team itself as the maintainer instead of individual GitHub users?

Relatedly, I see you pushed directly to that PR branch, `bump/nextstrain_cli` in the bioconda-recipes repo. I assume you have commit bits on the repo itself? Or is there some other way? (Most of us don't have upstream commit bits, so we submit PRs from https://github.com/nextstrain/bioconda-recipes instead.)

**Comment by corneliusroemer** [comment]
Yes, if you're a maintainer you can ask to get commit rights/be added to the team.

That's important to get speedy releases - as only those with commit rights can approve PRs which is necessary for merging.

So really the more important thing is to get 1-2 more people commit rights and approve (manually, or maybe through CI command) the PR once submitted by autobump.

Now at least I'll get a github notification that there's a PR for something that I co-maintain.
