### ISSUE TITLE
BUG(update): failed to register layer: sync /var/lib/docker/image/overlay2/layerdb/tmp/write-set-226670863/diff: input/output error

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/cli#206]
### Current Behavior
Running `nextstrain update` I get the following error:
```
failed to register layer: sync /var/lib/docker/image/overlay2/layerdb/tmp/write-set-226670863/diff: input/output error
```

### How to reproduce
Steps to reproduce the current behavior:
1. run `nextstrain update`

### Your environment
CLI version 4.1.0 on macos via conda

@tsibley

**Comment by tsibley** [comment]
There's not enough information here for me to debug this. I would guess that one cause might be you ran out of disk space. Since Docker runs in a VM on macOS hosts, it might be (depending on VM setup) that you can run out of space in the VM before you run out of physical space on the host. I think you'll need to help out with some more troubleshooting in order to get to the bottom of this.

**Comment by corneliusroemer** [comment]
Thanks for the tip - run out of storage indeed!
