### ISSUE TITLE
Should we auto-update the image?

### ISSUE THREAD

**Issue by trvrb** [nextstrain/cli#22]
I had an issue with Nextstrain view owing to my not having thought to run `nextstrain update` here with #21.

I had thought that it auto-updated. If possible, I would either have it auto-update before running `nextstrain build`, `nextstrain view`, etc..., or print that an update exists and you should run `nextstrain update`. I'd prefer the former. This is in analogy to `brew install` etc... that automatically runs `brew update`. Without this feature, there will be many gotcha moments when people have an issue and discover they needed to run `nextstrain update`.

If we're worried about pinning an image version I'd think to do something akin to `nextstrain pin TAGNAME`, where `TAGNAME` defaults to `LATEST`, which would give the auto-updating functionality.

**Comment by tsibley** [comment]
I don't think auto-updating is a good idea. It feels wrong to me and would very much surprise me when it happened. (For whatever it's worth, I was a big Homebrew user in my former job and hated the auto-update behaviour.)

The following scenario, made possible by auto-updating, seems at best very rude and at worst infuriating:

1. Person A is working on a pathogen build using `nextstrain build`, iterating on their work and steadily making progress.
2. They go to lunch having reached a good stopping point where things are working.
3. We release a new image.
4. They come back from lunch and the now their build is broken because when they ran `nextstrain build` again it pulled down the new image and hit some incompatibility.

If they're lucky, they'll see what happened.  If they're not, well they might be pretty confused and waste a lot of time. They also, crucially, don't have a good nor obvious way to get back to the working state. We've forced them to understand what updated and .

In the case of someone pulling down a new version of a build repo and needing a newer image, the error happens immediately and the situation is basically the same as when not using the image at all. The quickest way forward (when they don't care about why it's broken) is to check for updates by running `nextstrain update`, the same way you'd have to check for updates to augur/auspice/etc but with less work.

It's possible to imagine ways of versioning our images and being "smart" about auto-updates, but that gets pretty complicated pretty quick. I don't think we really have the infrastructure/process for programmatically tracking what's a breaking change vs. what's not in our own software much less for all of our deps baked into the images. The simpler thing, and the thing abiding by the principle of least surprise, is just to not auto-update.

**Comment by trvrb** [comment]
I agree with this assessment @tsibley. Thank you. I'm going to close this issue.
