### ISSUE TITLE
ENH: Compress batch job results using `.tar.zst` instead of `.zip` for 10x or more better compression ratio

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/cli#226]
### Context
Recently I've started using the batch job results to reproduce bugs.

I've noticed that the .zip folder is usually very large.

The main culprit seems to be that we compress the outputs using `.zip` which doesn't deal well with sequences.

I would recommend we switch compression to `.tar.zst`, it's got _much_ better compressions for sequences and is much faster to extract.

It's as simple as `tar caf target.tar.zst folder_to_compress`

@tsibley

**Comment by tsibley** [comment]
@corneliusroemer There's more to this than meets the eye.

The ZIP format is used here more for a container than for compression. ZIP archives have a table of contents, so we get random access to files in it without downloading the whole thing. This is super useful, and not something that you can replicate with tar without extra indexing bits (and those would have to be compression-aware too).

I think outputs that have specific compression needs (e.g. sequences really benefit from zstd's high compression) should probably be handled specifically by the workflow. But open to more general solutions here.

**Comment by corneliusroemer** [comment]
Fair point, yes zip allows extraction of single files (learned this recently).

So the solution may be to `zstd` compress big files before we zip them?

**Comment by tsibley** [comment]
> So the solution may be to `zstd` compress big files before we zip them?

For Nextstrain CLI, it's a fair bit of additional complexity to do this robustly for the general case. We'd have to make sure to `unzstd` such files when downloading them locally, but not `unzstd` things it didn't `zstd` in the first place (e.g. things the workflow left compressed with zstd), so you need a bit of additional metadata. We'd also have to separately track the original CRC or some other digest so we can preserve the ability to not extract files that didn't change:

https://github.com/nextstrain/cli/blob/550f0a909ae843493527955851586dc792894d71/nextstrain/cli/runner/aws_batch/s3.py#L122-L126

All in all, it's a bit simpler for the workflows themselves to arrange to compress big files. The workflow is the best positioned bit of code to know what's worth compressing and how.

**Comment by corneliusroemer** [comment]
>>And files above a certain size should be compressed? Say if it's >10MB, compress it, or something like that.
>This is not always a good heuristic and whether compression is worth it depends a lot on file contents. You could spend a lot of time compressing large binary blobs that were already internally compressed (or otherwise mostly incompressible). For example, think of .bam files and what not.

>Again, the workflow really is the best positioned bit of code to know what's worth compressing and how.

An extra zstd compression wouldn't take much time - doesn't zip recompress things already? So we'd just add another layer of compression?

The issue is that whenever we make a workflow that is to run on aws-batch, we don't seem to worry about big intermediate files. It's apparently usually not considered worth adding compression and uncompression steps for intermediate files just to make debugging locally easier.

The biggest files we deal with are fastas and they are much better compressed by zstd than by gzip or whatever zip uses. That's why it could be such a gain to zst compress certain things before including in the zip archive.

**Comment by tsibley** [comment]
> An extra zstd compression wouldn't take much time - doesn't zip recompress things already? So we'd just add another layer of compression?

Yes, ZIP will end up re-compressing things, but it doesn't try nearly as hard to compress stuff as other algorithms, so my sense is that it's not very time consuming. Maybe zstd would still be quick enough to always apply to each file though.

> The issue is that whenever we make a workflow that is to run on aws-batch, we don't seem to worry about big intermediate files. It's apparently usually not considered worth adding compression and uncompression steps for intermediate files just to make debugging locally easier.

Well, that seems like a social not a technical issue. :-) When writing/maintain workflows, I think we _should_ worry about big intermediate files and consider the CPU vs. storage tradeoff of not compressing them vs. zstd-compressing them in the workflow.

Again, my main point here is that the workflow really is the best positioned bit of code to know what's worth compressing and how (namely because someone has to make the choice to do so, rather than Nextstrain CLI having to guess at what's good or not).

I totally get why it's a pain to have huge archive sizes and why zstd really shines here. I want to avoid adding complexity here ([like having to track several bits of additional metadata for each archive member](https://github.com/nextstrain/cli/issues/226#issuecomment-1281260727)) when it might be better placed elsewhere, though.
