### ISSUE TITLE
ENH: Detect and warn user if their environment deviates from nextstrain-base

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/cli#282]
Out of curiosity, I pip installed a package in a `nextstrain shell --conda .`. The install went through without problem, but afterwards the installed package stayed around, even after `nextstrain update conda`.

While given our current implementation it makes sense that any pip-installed packages will stay around, this isn't necessarily a user expectation, especially given that the alternative `--docker` is reproducible and does not keep `pip` installed packages around.

It could be useful to check for any pip-installed packages at one or more of various points:
- `nextstrain update conda`
- `nextstrain shell --conda .`
- `nextstrain build --conda .`
- ...
and warn the user if we detect that their installation is different from nextstrain base (and suggest they `nextstrain setup conda --force` if they want to get back to a clean state.

An alternative is to make the appropriate package folder read only for everything but `nextstrain update`.

It's good to know that if someone says they use our managed `--conda` runtime, their actual system might differ, e.g. through `pip` installs. So we may want to ask for `pip list` if we suspect that this may be the case.

**Comment by tsibley** [comment]
I get the urge, but we can't reasonably make the Conda runtime as isolated as the Docker runtime, and if we could, we'd be reinventing parts of a container system like Docker or Singularity. We have to draw the line somewhere. We could try to handle Pip specifically, but I'm hesitant to do so because the _how_ is not clear cut.

Runtimes aren't super well documented (it's on the list), but the `nextstrain check-setup` docs do have this to say about the Conda runtime:

> [It's] more isolated and reproducible than your ambient runtime, but is less isolated and robust than the Docker runtime.

This issue seems to be a good example of that description.
