### ISSUE TITLE
Commands to manipulate (download, delete, list) deployed datasets and narratives

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/cli#36]
The `nextstrain deploy` command works great to upload data to the S3 buckets. It struck me that we may want to download data as well, especially for S3 buckets where authentication is required. (Maybe this would entail renaming `deploy`). We do this in auspice via https://github.com/nextstrain/auspice/blob/master/scripts/get-data.sh, which is a bit hacky... wildcards would be really good if possible.

**Comment by tsibley** [comment]
Hmm. This seems like scope creep to me. The `nextstrain` command isn't meant to be a general-purpose S3 manipulation tool: `aws s3` exists for that (and supports wildcards).

Note that S3 is just one possible destination for `nextstrain deploy` (albeit the only destination possible right now); future supported destinations might use SFTP, SCP, git, WebDAV, or other upload mechanisms. The intent is for `nextstrain deploy` to do what needs to be done to put locally built files at a location reachable by a deployed Nextstrain instance.

**Comment by jameshadfield** [comment]
with the implementation of private S3 buckets, we will need the ability to download / remove files (right now we can only do this via the AWS console).

**Comment by tsibley** [comment]
Ok, it sounds like we should re-envision the `nextstrain deploy` command.

What about something like the following, where `deploy` becomes `dataset upload`:

```
nextstrain dataset upload s3://nextstrain-data auspice/*.json
nextstrain dataset download s3://nextstrain-data/zika_tree.json some/dir/
nextstrain dataset delete s3://nextstrain-data/zika*

# Deploy will be an alias for `dataset upload`, so this still works, but asks
# you to start using the new command.
nextstrain deploy s3://nextstrain-data *.json
```

The `dataset delete` command will also take care of invalidating the CloudFront cache if necessary, the same way `deploy` does now.

**Comment by trvrb** [comment]
This seems very reasonable to me. I would find `nextstrain dataset download` useful in day-to-day work with flu. 

However, `dataset` seems slightly non-perfect semantically, but I don't have a better suggestion.

I'm 50/50 on whether I prefer:

```
nextstrain dataset upload s3://nextstrain-data auspice/*.json
nextstrain dataset download s3://nextstrain-data/zika_tree.json some/dir/
nextstrain dataset delete s3://nextstrain-data/zika*
```

or 

```
nextstrain retrieve s3://nextstrain-data auspice/*.json
nextstrain deploy s3://nextstrain-data/zika_tree.json some/dir/
nextstrain remove s3://nextstrain-data/zika*
```

**Comment by tsibley** [comment]
I agree `dataset` isn't quite on the nose, especially since it'd (intentionally) work for narratives too. I'm hesitant to lift up its subcommands to the top-level though.

I do prefer upload/download over deploy/retrieve. Deploy has more connotations than I think we want (I regret this choice) and isn't a common term for non-developers, whereas upload/download are widely understood by even non-developers.

I definitely want to make sources first-class things understood by the CLI, but I think that's a different scope of work for the future. The current design of the `deploy` command is set up to support different kinds of destinations (although it only supports S3 right now), and I'll maintain this in whatever additions I make for download/delete.

**Comment by tsibley** [comment]
> I'm hesitant to lift up its subcommands to the top-level though.

That said, it may still be the right choice!

**Comment by trvrb** [comment]
I see the logic of the subcommand and think generally cleaner, but without `dataset` feeling right I think semantically better to just do `nextstrain upload`, `nextstrain download`, `nextstrain delete`. Other options I just considered, but didn't really like `nextstrain io upload`, `nextstrain file upload`, `nextstrain remote upload`.

**Comment by tsibley** [comment]
Sounds good to me.

**Comment by jameshadfield** [comment]
I have no comment on the naming but the functionality sounds perfect.

**Comment by tsibley** [comment]
I guess we'll also need a `nextstrain list` command?

(I'd plan to alias `delete` to `rm` and `list` to `ls`.)

**Comment by jameshadfield** [comment]
I said I wouldn't comment on naming, but having taught `nextstrain deploy` over the past 2 weeks here is a comment:

"list", "delete", "upload", "download" (and who knows, there maybe more in the future, e.g. "move") are all part of the same concept in that they interact with a "source" (or "group", not sure about [terminology](https://github.com/tsibley/blab-standup/blob/master/2019-09-06.md#urls)), and not the local computer / aws build / docker build. This should be clear from the command.

**Comment by tsibley** [comment]
Yeah, that commonality is a big reason why I'd prefer a subcommand to collect and identify them all, and why I'm hesitant to make them all top-level commands.

I dismissed `dataset` earlier, but coming back to it, maybe we do:

```
nextstrain dataset {upload/deploy,download,delete,list} …
nextstrain narrative {upload/deploy,download,delete,list} …
```

`nextstrain deploy` would become an alias for `nextstrain dataset upload`.

The backing code (currently what's in `nextstrain/cli/deploy/*` as used by `nextstrain/cli/command/deploy.py`) would be largely shared between both `nextstrain dataset` and `nextstrain narrative`, but the `list`ing can specific to one type of file or the other and we can be dataset- or narrative-specific in help text.

**Comment by tsibley** [comment]
I spent some time yesterday and today implementing these commands under working names since the real names are still TBD. We should decide on the final names/structure so I can finish this up sooner than later. The basics are mostly there but there is still some refining of behaviour and documentation to round it out.

**Comment by trvrb** [comment]
Nice! I was just doing some work / thinking about the proposal I had earlier in the summer to have entrypoint for builds start with downloading a flat file from S3 rather than calling out to fauna. My thought was to mirror data.nextstrain.org/zika.json with something like data.nextstrain.org/zika_sequences.fasta and data.nextstrain.org/zika_metadata.tsv. We don't have to move in this direction, but I can see creep of more file types than `dataset` and `narrative`. But that doesn't mean that `dataset` and `narrative` aren't good things to have. 

That said, I am maybe coming around to `nextstrain remote {upload,download,delete,list} …`.

**Comment by tsibley** [comment]
Nod. During my implementation so far, I was realizing that separate `dataset` and `narrative` commands would add a lot of UI duplication to the CLI. So I was thinking better to have a single command like `remote` which, if desired, then could have separate filter options for file "types" (dataset, narrative, etc.).

**Comment by trvrb** [comment]
Thanks Tom. After thinking more, my preference is `nextstrain remote upload/download/etc`. If you prefer something else happy to go with that as well.
