### ISSUE TITLE
What is the remit of CLI?

### ISSUE THREAD

**Issue by trvrb** [nextstrain/cli#6]
I want to have a clear remit for CLI. How does it fall in relation to augur and auspice? Is the current direction of sound one?

I would imagine the CLI making possible the following workflow:
- `nextstrain build --aws --repo nextstrain/zika`: starts jobs running via AWS batch and resulting JSON files go to an S3 bucket
- `nextstrain fetch`: pulls down data from this bucket to a local directory
- `nextstrain view`: to look at this data in auspice
- `nextstrain deploy`: to push JSONs live

Or a local build is run with:
- `nextstrain build .`: starts job running locally
- `nextstrain view`: to look JSONs in auspice
- `nextstrain deploy`: to push JSONs live

This workflow is used for established builds that are debugged and working. Debugging and getting things working takes place within augur. Augur doesn't concern itself with moving files about. `deploy` takes place after viewing in auspice. Not necessarily advocating this exact solution, but seems like a comfortable direction. `nextstrain` takes care of the Nextstrain logic, pushing builds live, fetching builds, etc... that is outside the scope of augur or auspice individually.

In general, I'd like to figure out a way to best frame `nextstrain/cli`. What is its remit? What is its interface? Is this a good general direction, or do people have other things in mind?

**Comment by tsibley** [comment]
Thanks for laying this out. Although I've done a poor job of expressing it, this is essentially what I've intended for the CLI to be all along.

I envisioned things like `nextstrain build --singularity` for usage on rhino/places where Docker isn't available and `nextstrain build --local` for running outside a container image all together (i.e. within a local conda environment).

If people seem mostly happy with the general direction, then I think there are some good followup questions about interface to discuss re: the experience of remote builds and fetching results.

**Comment by tsibley** [comment]
Here's where my brain is at regarding future directions for the CLI, by way of
examples that are hopefully mostly self-explanatory.  Please ask for clarification
where the examples are unclear!  Each example shows only the relevant options
and arguments, but options from each section may be combined in any way
desired.


### Deployment

    nextstrain deploy s3://nextstrain-staging auspice/*.json
    nextstrain deploy s3://nextstrain-data    auspice/*.json


### Build directory locations

    nextstrain build .
    nextstrain build /fh/fast/bedford_t/zika
    nextstrain build https://github.com/nextstrain/zika
    nextstrain build https://github.com/nextstrain/zika#some-branch

Remote git repos may want to follow pip's lead and use URLs like
`git+https://github.com/nextstrain/zika` instead (with the leading `git+`).


### Build execution locations

    nextstrain build                (defaults to --docker)
    nextstrain build --docker
    nextstrain build --singularity
    nextstrain build --aws
    nextstrain build --local        (runs outside any container image,
                                     in whatever the current environment is,
                                     e.g. conda, virtualenv, etc)


### Remote components (--augur, --auspice, etc)?

Components within the container image can be replaced on demand using the
--augur, --auspice, etc options.  Currently they only work with local
filesystem paths, as in the first line below, but it might be desirable to
support remote locations as well for testing/development purposes.

    nextstrain build --augur ~/blab/augur/
    nextstrain build --augur https://github.com/nextstrain/augur
    nextstrain build --augur https://github.com/nextstrain/augur#some-branch


### Remote build experience

One idea for how remote builds might work interface-wise:

    $ nextstrain build --aws .
    Starting build of ~/nextstrain/zika on AWS Batch…

    Results will be available at:

        https://.../37c0d9d765dc17fda57225759a98b4dc2599a6d3/

    You can fetch them using:

        nextstrain fetch-build 37c0d9d765dc17fda57225759a98b4dc2599a6d3

    or by using build's --fetch option next time.


    $ nextstrain fetch-build 37c0d9d765dc17fda57225759a98b4dc2599a6d3
    Waiting for build to finish…

    Downloading auspice/zika_tree.json
    Downloading auspice/zika_meta.json
    Downloading data/zika.fasta
    Downloading results/aligned.fasta.log
    Downloading results/filtered.fasta
    Downloading results/aligned.fasta.pre_aligner.fasta
    Downloading results/country.mugration_model.txt
    ...


or as one step:

    $ nextstrain build --aws --fetch .
    Starting build of ~/nextstrain/zika on AWS Batch…

    Results will be available at:

        https://.../37c0d9d765dc17fda57225759a98b4dc2599a6d3/

    Waiting for build to finish…

    Downloading auspice/zika_tree.json
    Downloading auspice/zika_meta.json
    Downloading data/zika.fasta
    Downloading results/aligned.fasta.log
    Downloading results/filtered.fasta
    Downloading results/aligned.fasta.pre_aligner.fasta
    Downloading results/country.mugration_model.txt
    ...


### Smoke testing several builds remotely after augur changes

James wants to be able to smoke test several or all pathogen builds after
pushing up an augur topic/feature branch.  Using some of the primitives
sketched out above, that might be accomplished by something like:

    parallel \
        nextstrain build --aws --fetch --augur https://github.com/nextstrain/augur#some-branch \
            https://github.com/nextstrain/{} \
        ::: zika tb WNV mumps

which could be added to a local alias or otherwise wrapped up into another
command.

We could use a similar command in a Travis CI config to automatically
smoke-test builds when augur changes.

### Paths

I think that all commands should take explicit paths to local/remote files
(hence things like `auspice/*.json` or `.` or `https://github.com/...` above).
However, it might be desirable to add some conventional defaults if no explicit
paths are given to a command that expects them.  For `deploy`, that might be
automatically looking at all `*.json` files in an `auspice/` subdirectory.  For
`build` that might be assuming the current directory.  The disadvantage is
that, while the surficial syntax is nicer, it makes it harder to explain when
the defaults apply and when they don't.  Explicit-ness has a nice way of being
more apparent what's happening.

**Comment by tsibley** [comment]
Further thoughts on and the current state of the deploy command: https://github.com/tsibley/blab-standup/blob/master/2018-07-25.md#25-july-2018

**Comment by tsibley** [comment]
Currently working on running builds outside of any container image, e.g. `nextstrain build --native zika`, by relying on native installations of snakemake, augur, etc, as I described above.  There's a (very!) work-in-progress on the [`wip/native-runner` branch](https://github.com/nextstrain/cli/compare/master...wip/native-runner).

The idea of doing this now is to lay groundwork for an AWS Batch runner. The details of how to support a second runner in the CLI are largely the same, but it's easier to do with native execution since I don't also have to nail down the remote execution at the same time.

**Comment by tsibley** [comment]
Closing this issue as it never developed into a conversation (lack of interest?) and meanwhile development of the project proceeded based on other feedback forums.
